import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import fg from "fast-glob";
import { parse as parseYaml } from "yaml";
import { VERSION } from "../version.js";
import { readFrontmatter } from "./frontmatter.js";
import { stripManagedBlock, writeManagedBlock } from "./managed-block.js";
import { type Profile, type ResolvedLaw, resolveLaws } from "./resolve.js";
import { DEFAULT_TOOLS, readEepTools, type ToolToken } from "./tools.js";
import type { PackLayout } from "./vendor.js";

const PROFILE_BLOCK_TEXT = {
  greenfield:
    "Profile: greenfield. Every law blocks. Scaffold with eep init output patterns; never hand roll what a template covers.",
  evolving:
    "Profile: evolving. New and modified code must comply. Do not refactor untouched code in the same pull request.",
} as const;

// The authority sentence is part of the footer rather than a section of its own: an agent that
// reads eep.yaml and edits it expecting the gate to change would be wrong, and the last paragraph
// of the instructions is where that correction is still being read.
const VERIFY_FOOTER =
  "Before declaring work done run `eep verify`. On failure run `eep explain <LAW-ID>`. " +
  "Configuration authority is .eep/lock.yaml; eep.yaml is a human readable record only.";

// The two component capable surfaces, each a co owned markdown file carrying the same generated
// block, and each written only when its tool is in the selection. An agent reads one or the other
// depending on the tool that spawned it, so the two generated regions must never drift; what
// surrounds the block is the repository's own and may differ between them. CLAUDE.md pairs with the
// claude token, AGENTS.md with the agents token, at the root and in every component directory.
const CLAUDE_FILE_NAME = "CLAUDE.md";
const AGENTS_FILE_NAME = "AGENTS.md";
const AGENT_FILE_NAMES = [AGENTS_FILE_NAME, CLAUDE_FILE_NAME] as const;

// Which component file name each of the two component capable tokens owns. copilot and cursor are
// absent because they write no component files: they are root only whatever the layout.
const COMPONENT_FILE_FOR_TOKEN: Partial<Record<ToolToken, string>> = {
  claude: CLAUDE_FILE_NAME,
  agents: AGENTS_FILE_NAME,
};

// The two tool surfaces beyond the agent pair, both at the repository root and both carrying the
// identical root body, each written only when its tool is selected. GitHub Copilot reads a managed
// block inside a markdown file the repository may already own, so it is co owned exactly like
// CLAUDE.md: user content around the block is preserved. Cursor reads a rule file eep owns outright,
// namespaced eep.mdc, so it carries no block and a team's other .cursor/rules/*.mdc are never
// touched. Both are root only, one each; component directories carry only CLAUDE.md and AGENTS.md.
export const COPILOT_INSTRUCTIONS_FILE = ".github/copilot-instructions.md";
export const CURSOR_RULE_FILE = ".cursor/rules/eep.mdc";

// The frontmatter Cursor requires at the top of a rule file. alwaysApply true loads the rule into
// every request in the repository rather than only when a path glob matches, which is the behavior
// the agent pair and the Copilot file already have. The instruction body sits below it, unchanged
// from what every other root surface carries.
const CURSOR_FRONTMATTER = [
  "---",
  "description: Engineering Excellence Program doctrine and golden paths",
  "alwaysApply: true",
  "---",
].join("\n");

const ROUTER_HEADING = "## Components and where their golden paths live";

// The one sentence under the router table. It has to answer the only question the table raises:
// having found the row for the directory I am working in, what am I supposed to do with it.
const ROUTER_SENTENCE =
  "Agents working inside a component directory should read that directory's CLAUDE.md before " +
  "writing code there, and agents touching delivery or container concerns should read the " +
  "vendored path first.";

// What the Component column says for a pack with no pinned workdir: its contribution is repository
// level (workflows, container definitions), so there is no one directory to name.
const ROOT_COMPONENT = "repo root";

const LAW_TABLE_HEADING = "## The laws in force";

// The line every component instruction file opens with, minus the pack name and version, and the
// substring that identifies a file as one this generator owns. Nothing else in a repository writes
// it, so a file carrying it can be deleted on a narrowing sync without a lock diff to consult
// (see removeStaleComponentFiles).
const COMPONENT_HEADER_MARKER = "golden path (generated by eep ";

// Where a stale component instruction file can be: one or two directories down. Deeper nesting is
// not scanned, and neither are the four trees no generated file of ours ever lands in, so a
// narrowing sync in a large repository stays a cheap, shallow walk rather than a full tree crawl.
const COMPONENT_SCAN_PATTERNS = [
  "*/CLAUDE.md",
  "*/AGENTS.md",
  "*/*/CLAUDE.md",
  "*/*/AGENTS.md",
] as const;
const COMPONENT_SCAN_IGNORE = [
  "**/node_modules/**",
  "**/.git/**",
  "**/.venv/**",
  "**/.eep/**",
] as const;

function readYamlObject(path: string): Record<string, unknown> {
  const parsed: unknown = parseYaml(readFileSync(path, "utf8"));
  if (parsed === null || typeof parsed !== "object") return {};
  return parsed as Record<string, unknown>;
}

/**
 * The pack list out of a lock document, with each pack's pinned workdir.
 *
 * lock.yaml's packs entries are {name, version, workdir?} objects (see vendor.ts). The version is
 * not read here; the name drives resolveLaws and locates the vendored pack, and the workdir decides
 * whether this pack has a component directory of its own to carry its golden path.
 */
function toPackLayout(value: unknown): PackLayout[] {
  if (!Array.isArray(value)) return [];
  const packs: PackLayout[] = [];
  for (const entry of value) {
    if (entry === null || typeof entry !== "object") continue;
    const name = (entry as { name?: unknown }).name;
    if (typeof name !== "string") continue;
    const workdir = (entry as { workdir?: unknown }).workdir;
    packs.push({ name, workdir: typeof workdir === "string" && workdir !== "" ? workdir : null });
  }
  return packs;
}

/**
 * The pack layout `${targetDir}/.eep/lock.yaml` records, or an empty list when there is no lock.
 *
 * Exported for the callers that have to name the files a generate pass wrote after the fact: init
 * commits them, and only the lock knows which directories they landed in.
 */
export function lockedPackLayout(targetDir: string): PackLayout[] {
  const lockPath = join(targetDir, ".eep", "lock.yaml");
  if (!existsSync(lockPath)) return [];
  return toPackLayout(readYamlObject(lockPath).packs);
}

/**
 * Whether this layout gets component instruction files and a router at the root, rather than one
 * document carrying every pack's golden path inline.
 *
 * Two conditions, either of which is enough. More than one pack means the single document was
 * about to become a concatenation of golden paths for stacks most agents editing this repository
 * will never touch. A pinned workdir means there is a directory an agent can be working inside,
 * which is the only place a component scoped instruction file can be read from at all.
 */
export function isMultiLayout(packs: readonly PackLayout[]): boolean {
  return packs.length > 1 || packs.some((pack) => pack.workdir !== null);
}

// The component file names the selection actually writes: CLAUDE.md when claude is chosen, AGENTS.md
// when agents is chosen, in that stable order. copilot and cursor contribute none.
function componentFileNames(tools: readonly ToolToken[]): string[] {
  return AGENT_FILE_NAMES.filter((name) =>
    tools.some((token) => COMPONENT_FILE_FOR_TOKEN[token] === name),
  );
}

/**
 * Every component instruction file this layout and selection writes, as target relative paths.
 *
 * Empty for a single component layout, which writes nothing outside the repository root, and empty
 * for a selection that includes neither claude nor agents. Used by the commands that have to name
 * the files a generate pass produced: the plan printed before a write, and the artifacts init
 * commits after one.
 */
export function componentInstructionFiles(
  packs: readonly PackLayout[],
  tools: readonly ToolToken[],
): string[] {
  if (!isMultiLayout(packs)) return [];
  const names = componentFileNames(tools);
  const files: string[] = [];
  for (const pack of packs) {
    if (pack.workdir === null) continue;
    for (const name of names) files.push(`${pack.workdir}/${name}`);
  }
  return files;
}

/**
 * The root surface files this selection writes, as target relative paths, in a stable order.
 *
 * One entry per chosen tool: CLAUDE.md, AGENTS.md, the Copilot file, the Cursor rule. Empty for the
 * "none" selection. The commands use it to plan and to commit exactly the root files a generate pass
 * produces, without re listing the ones the selection leaves out.
 */
export function rootSurfaceFiles(tools: readonly ToolToken[]): string[] {
  const files: string[] = [];
  if (tools.includes("claude")) files.push(CLAUDE_FILE_NAME);
  if (tools.includes("agents")) files.push(AGENTS_FILE_NAME);
  if (tools.includes("copilot")) files.push(COPILOT_INSTRUCTIONS_FILE);
  if (tools.includes("cursor")) files.push(CURSOR_RULE_FILE);
  return files;
}

function toProfile(value: unknown): Profile {
  if (value === "greenfield" || value === "evolving" || value === "steady") return value;
  throw new Error(`eep: unknown profile "${String(value)}" in .eep/lock.yaml`);
}

// greenfield and evolving are the only profiles a lock.yaml can carry once resolveLaws has run
// without throwing (it rejects "steady" itself, see generateAgentFiles below), so the throw here
// is unreachable in practice. It exists so this function is total over the Profile type without a
// cast, and, if it is ever reached, it raises the exact message resolveLaws raises for "steady".
function profileBlock(profile: Profile): string {
  if (profile === "greenfield") return PROFILE_BLOCK_TEXT.greenfield;
  if (profile === "evolving") return PROFILE_BLOCK_TEXT.evolving;
  throw new Error("steady enforcement ships in a later release; run greenfield or evolving");
}

// Drops a trailing "---" rule followed by a "*Authored by" line, when both are the last
// non-empty lines of the body, so a document's per-file attribution footer is not repeated once
// per section in the assembled agent instructions.
function stripFooter(body: string): string {
  const lines = body.split("\n");

  const trimTrailingBlankLines = (): void => {
    while (lines.length > 0 && (lines[lines.length - 1] ?? "").trim() === "") {
      lines.pop();
    }
  };

  trimTrailingBlankLines();
  const last = lines[lines.length - 1];
  if (last?.trim().startsWith("*Authored by")) {
    lines.pop();
    trimTrailingBlankLines();
    const rule = lines[lines.length - 1];
    if (rule !== undefined && rule.trim() === "---") {
      lines.pop();
    }
  }
  trimTrailingBlankLines();

  return lines.join("\n");
}

// Frontmatter stripped via readFrontmatter's .body, footer stripped via stripFooter, then trimmed
// of the leading/trailing blank lines both of those leave behind.
function readStrippedBody(path: string): string {
  const { body } = readFrontmatter(path);
  return stripFooter(body).trim();
}

// Packs vendor at .eep/packs/<kind>/<name>/ (kind mirrors the corpus's own packs/<kind>/<name>/
// shape; see vendor.ts), so the kind segment is globbed rather than assumed. The result is target
// relative, because it is printed into the instructions as often as it is read from disk.
function findVendoredPackDir(targetDir: string, packName: string): string {
  const matches = fg.sync(`.eep/packs/*/${packName}/pack.yaml`, { cwd: targetDir }).sort();
  const first = matches[0];
  if (first === undefined) {
    throw new Error(`eep: pack "${packName}" not found in ${targetDir}/.eep/packs`);
  }
  return dirname(first);
}

function vendoredStackPath(targetDir: string, packName: string): string {
  const path = `${findVendoredPackDir(targetDir, packName)}/STACK.md`;
  if (!existsSync(join(targetDir, path))) {
    throw new Error(`eep: STACK.md not found for pack "${packName}" in ${targetDir}/.eep/packs`);
  }
  return path;
}

function readStackBody(targetDir: string, packName: string): string {
  return readStrippedBody(join(targetDir, vendoredStackPath(targetDir, packName)));
}

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function severityCell(law: ResolvedLaw): string {
  return law.declined !== null ? "declined" : law.severity;
}

function checkCell(law: ResolvedLaw): string {
  if (law.declined !== null) return escapeTableCell(law.declined);
  if (law.check === null) return "";
  const command =
    law.check.kind === "builtin" ? `builtin: ${law.check.command}` : law.check.command;
  return `\`${escapeTableCell(command)}\``;
}

const LAW_TABLE_HEADER = "| Law | Pack | Title | Severity | Check |";
const LAW_TABLE_DIVIDER = "| --- | --- | --- | --- | --- |";

function lawRow(law: ResolvedLaw): string {
  return `| ${law.id} | ${escapeTableCell(law.pack)} | ${escapeTableCell(law.title)} | ${severityCell(law)} | ${checkCell(law)} |`;
}

// One row per resolved entry, so a law two packs both implement appears once per pack with that
// pack's own check command. An agent reading this table has to be able to see that the coverage
// law it is about to satisfy is gated twice, by two different commands, in two different
// directories.
function buildLawTable(laws: ResolvedLaw[]): string {
  return [LAW_TABLE_HEADING, "", LAW_TABLE_HEADER, LAW_TABLE_DIVIDER, ...laws.map(lawRow)].join(
    "\n",
  );
}

/**
 * The same table with every decline collapsed to one row per pack.
 *
 * A decline is a fact about the pack, not an instruction to the agent reading this file: it says
 * this stack proves nothing about that law, and the reason is a paragraph in the pack's own
 * manifest. Five packs decline forty three laws between them, which is more rows than every law
 * actually in force put together, all of them telling an agent about work it is not being asked to
 * do. The implemented rows are kept exactly as the single component layout writes them, because
 * those are the rows the gate will judge this repository by.
 */
function buildSlimLawTable(
  targetDir: string,
  laws: ResolvedLaw[],
  packs: readonly PackLayout[],
): string {
  const rows = laws.filter((law) => law.declined === null).map(lawRow);

  for (const pack of packs) {
    const declined = laws.filter((law) => law.pack === pack.name && law.declined !== null).length;
    if (declined === 0) continue;
    // Agreement matters in a document a program asks people to read: one pack declines exactly one
    // law, and "1 laws declined with reasons" is the kind of generated sentence that tells a reader
    // nobody looked at the output.
    const subject =
      declined === 1 ? "1 law declined with a reason" : `${declined} laws declined with reasons`;
    const manifest = `${findVendoredPackDir(targetDir, pack.name)}/pack.yaml`;
    rows.push(`| declined | ${escapeTableCell(pack.name)} | ${subject} | see ${manifest} | - |`);
  }

  return [LAW_TABLE_HEADING, "", LAW_TABLE_HEADER, LAW_TABLE_DIVIDER, ...rows].join("\n");
}

/**
 * The router: one row per pack, saying where that pack's golden path is and which directory it
 * governs.
 *
 * A pack with a pinned workdir points at the instruction file this same run writes into that
 * directory, which is what the agent's own tooling will load when it starts working there. A pack
 * without one points at the vendored corpus copy, because a repository level contribution has no
 * directory of its own to be read from.
 */
function buildRouterSection(targetDir: string, packs: readonly PackLayout[]): string {
  const rows = packs.map((pack) => {
    const component = pack.workdir ?? ROOT_COMPONENT;
    const location =
      pack.workdir === null ? vendoredStackPath(targetDir, pack.name) : `${pack.workdir}/CLAUDE.md`;
    return `| ${escapeTableCell(component)} | ${escapeTableCell(pack.name)} | ${escapeTableCell(location)} |`;
  });

  return [
    ROUTER_HEADING,
    "",
    "| Component | Pack | Golden path location |",
    "| --- | --- | --- |",
    ...rows,
    "",
    ROUTER_SENTENCE,
  ].join("\n");
}

/**
 * One component's instructions: the golden path for the stack that lives in this directory, and
 * nothing else.
 *
 * No constitution and no law table, on purpose. Both are repository wide, both are already in the
 * root instructions every agent loads, and duplicating them per component is how the root document
 * reached 940 lines in the first place. The one line above the golden path exists because the
 * single thing a component reader can get wrong is where the gate runs from: there is exactly one
 * .eep tree, at the root, so `eep verify` inside the component can only ever report that it found
 * no configuration.
 */
function buildComponentBody(packName: string, stackBody: string): string {
  return `${[
    `# ${packName} ${COMPONENT_HEADER_MARKER}${VERSION}; component of the repository root instructions; do not edit)`,
    "The gate runs from the repository root: `eep verify`.",
    stackBody,
  ].join("\n\n")}\n`;
}

/**
 * Reconciles one co owned managed block surface with the selection: write the block when the tool is
 * chosen, or strip eep's block back out when it is not, preserving whatever the file carries around
 * it either way.
 *
 * The strip half is the deselection path (see stripManagedSurface): a file that was nothing but our
 * block is deleted, a file where a team wrote prose around it keeps that prose and loses only the
 * block, and a file that never carried our block is left untouched. `relPath` names the file in a
 * malformed block warning, so the reader sees the path they typed rather than a temporary directory.
 */
function syncManagedSurface(
  absPath: string,
  relPath: string,
  body: string,
  selected: boolean,
): void {
  if (selected) {
    writeManagedBlock(absPath, relPath, body);
  } else {
    stripManagedSurface(absPath);
  }
}

/**
 * Removes eep's managed block from a co owned surface while keeping everything else the file holds.
 *
 * The counterpart to writeManagedBlock, used when a tool is deselected. A file that was nothing but
 * our block is deleted (eep created it, so nothing of the team's is lost); a file where prose sits
 * around our block keeps that prose and loses only the block; a file that never carried our block, or
 * is absent, is left exactly as it is. Shares stripManagedBlock with removeStaleComponentFiles, so a
 * deselected Copilot file is treated exactly as a dropped component's CLAUDE.md is.
 */
function stripManagedSurface(absPath: string): void {
  if (!existsSync(absPath)) return;
  const content = readFileSync(absPath, "utf8");
  const remainder = stripManagedBlock(content);
  if (remainder === content) return;
  if (remainder === null) {
    rmSync(absPath, { force: true });
    return;
  }
  writeFileSync(absPath, remainder);
}

/**
 * Writes the Cursor rule as a whole file eep owns.
 *
 * No managed block: the file is namespaced eep.mdc, so eep owns every byte of it and rewrites it in
 * full each run, which leaves a team's other .cursor/rules/*.mdc untouched by construction. The
 * frontmatter Cursor requires sits above the same body the agent pair and the Copilot file carry.
 * Creates .cursor/rules, which a repository that has never used Cursor will not have.
 */
function writeCursorRule(targetDir: string, body: string): void {
  const absPath = join(targetDir, ".cursor", "rules", "eep.mdc");
  mkdirSync(dirname(absPath), { recursive: true });
  writeFileSync(absPath, `${CURSOR_FRONTMATTER}\n\n${body}`);
}

/**
 * Reconciles all four root surfaces with the selection, so an agent reaching this repository through
 * a chosen tool is held to the identical instructions and a tool the team did not choose leaves no
 * file behind.
 *
 * CLAUDE.md, AGENTS.md, and the Copilot file are co owned: each is written as a managed block when
 * its tool is chosen and stripped back out when it is not, preserving user content either way (see
 * syncManagedSurface). The Cursor rule is eep's own file: written whole when cursor is chosen, deleted
 * when it is not. All four take the same body, so there is one instruction text and up to four ways
 * in, never several that can drift apart.
 */
function writeRootSurfaces(
  targetDir: string,
  body: string,
  selected: ReadonlySet<ToolToken>,
): void {
  syncManagedSurface(
    join(targetDir, CLAUDE_FILE_NAME),
    CLAUDE_FILE_NAME,
    body,
    selected.has("claude"),
  );
  syncManagedSurface(
    join(targetDir, AGENTS_FILE_NAME),
    AGENTS_FILE_NAME,
    body,
    selected.has("agents"),
  );
  syncManagedSurface(
    join(targetDir, ".github", "copilot-instructions.md"),
    COPILOT_INSTRUCTIONS_FILE,
    body,
    selected.has("copilot"),
  );
  if (selected.has("cursor")) {
    writeCursorRule(targetDir, body);
  } else {
    rmSync(join(targetDir, ".cursor", "rules", "eep.mdc"), { force: true });
  }
}

/**
 * Reconciles one component directory's two agent files with the selection.
 *
 * The composed layout's per component golden path is carried in CLAUDE.md and AGENTS.md, each written
 * when its tool is chosen and stripped when it is not, exactly as at the root. copilot and cursor have
 * no component files, so they are not touched here.
 */
function writeComponentPair(
  dir: string,
  relDir: string,
  body: string,
  selected: ReadonlySet<ToolToken>,
): void {
  syncManagedSurface(
    join(dir, CLAUDE_FILE_NAME),
    `${relDir}/${CLAUDE_FILE_NAME}`,
    body,
    selected.has("claude"),
  );
  syncManagedSurface(
    join(dir, AGENTS_FILE_NAME),
    `${relDir}/${AGENTS_FILE_NAME}`,
    body,
    selected.has("agents"),
  );
}

function firstLine(text: string): string {
  return text.split("\n", 1)[0] ?? "";
}

/**
 * Deletes the component instruction files a previous run wrote into directories this run does not
 * write into.
 *
 * Narrowing the pack set is the documented way to drop a framework, and the dropped pack's
 * component instructions have to go with it: an agent that kept reading `frontend/CLAUDE.md` would
 * be following a golden path this repository no longer enforces, and nothing in the root document
 * would contradict it. The same applies when a repository composed of several components collapses
 * back to one, where the whole layout stops having component files at all.
 *
 * Ownership is read off the file rather than diffed out of the previous lock, which this function
 * cannot see (vendorInto has already rewritten it by the time anything generates). Only what this
 * program wrote is removed: a file that is nothing but our managed block goes entirely, a file whose
 * managed block sits under content someone else wrote keeps that content and loses only the block,
 * and a hand written CLAUDE.md carrying no block at all is never touched. A file left over from
 * 0.1.x or 0.2.x is generated whole (its first line carries the component header) and is deleted as
 * it always was.
 */
function removeStaleComponentFiles(targetDir: string, keep: ReadonlySet<string>): void {
  const matches = fg
    .sync([...COMPONENT_SCAN_PATTERNS], {
      cwd: targetDir,
      ignore: [...COMPONENT_SCAN_IGNORE],
      onlyFiles: true,
      suppressErrors: true,
    })
    .sort();

  for (const relPath of matches) {
    if (keep.has(dirname(relPath))) continue;
    const absPath = join(targetDir, relPath);
    const content = readFileSync(absPath, "utf8");
    if (firstLine(content).includes(COMPONENT_HEADER_MARKER)) {
      rmSync(absPath, { force: true });
      continue;
    }
    const remainder = stripManagedBlock(content);
    if (remainder === content) continue;
    if (remainder === null) {
      rmSync(absPath, { force: true });
      continue;
    }
    writeFileSync(absPath, remainder);
  }
}

/**
 * Builds this repository's agent instructions from its vendored `.eep/` tree and writes them into the
 * surfaces the tool selection names, stripping eep's footprint from any surface the selection leaves
 * out.
 *
 * The selection is a set of tool tokens (see lib/tools.ts), passed in or read from eep.yaml, defaulting
 * to the AGENTS.md baseline when neither answers. Each chosen tool gets its file carrying the identical
 * body: CLAUDE.md and AGENTS.md and the Copilot file as co owned managed blocks (user content around
 * them preserved), the Cursor rule as eep's own whole file. Each unchosen tool has its block stripped
 * back out (or its rule deleted), so deselecting a tool on a later run removes exactly what it wrote and
 * nothing a team wrote around it. A selection of none writes no agent files at all.
 *
 * The layout forks on what the lock records, and only there (see isMultiLayout). The root surfaces are
 * reconciled in both layouts; the component pair (CLAUDE.md and AGENTS.md only, per the selection) is
 * composed layout only, because copilot and cursor are root surfaces whatever the layout.
 *
 * A single component repository gets one document, exactly as every release before this one wrote
 * it: the generated-file header, the profile enforcement block, the constitution, the pack's
 * STACK.md golden path, the resolved law table, and a closing reminder to run `eep verify`.
 *
 * A repository with several packs, or with a pack pinned to a component directory, gets the same
 * document with the golden paths taken out of it and a router put in their place, plus one
 * instruction file per component directory carrying that component's golden path. This is
 * interface segregation applied to the one interface this program owns: an agent editing the
 * backend was being handed five stacks it will never touch, in a file loaded into every
 * conversation, and the law table it needed was underneath forty three rows about laws no pack
 * proves. The root keeps everything that is true of the whole repository (the constitution, the
 * laws in force, the gate) and points at the rest.
 *
 * Regeneration rewrites every managed block the selection keeps, strips every surface it drops, and
 * removes the component blocks a narrower pack set leaves behind (see removeStaleComponentFiles), so
 * the generated regions always reflect the current lock and the current selection together. Throws
 * when `${targetDir}/.eep/lock.yaml` is absent (no vendored corpus to read), and propagates whatever
 * resolveLaws throws, including its rejection of a "steady" profile.
 */
export function generateAgentFiles(targetDir: string, tools?: readonly ToolToken[]): void {
  const lockPath = join(targetDir, ".eep", "lock.yaml");
  if (!existsSync(lockPath)) {
    throw new Error("eep: no .eep found; run eep adopt first");
  }

  // The selection drives which surfaces are written; the commands pass it explicitly (they just
  // resolved and stored it), and a direct call falls back to the stored eep.yaml selection, then to
  // the AGENTS.md baseline. A set makes the per surface "is this tool chosen" checks below cheap.
  const selected = new Set(tools ?? readEepTools(targetDir) ?? DEFAULT_TOOLS);

  const lock = readYamlObject(lockPath);
  const packs = toPackLayout(lock.packs);
  const packNames = packs.map((pack) => pack.name);
  const profile = toProfile(lock.profile);
  const corpusDir = join(targetDir, ".eep");

  // Resolved first so an invalid profile (or any other resolveLaws failure) surfaces before any
  // output is assembled, using the exact error resolveLaws itself raises.
  const laws = resolveLaws(packNames, profile, corpusDir);

  const preamble = [
    `# Agent instructions (generated by eep ${VERSION}; do not edit, regenerate with eep adopt)`,
    profileBlock(profile),
    readStrippedBody(join(corpusDir, "CONSTITUTION.md")),
  ];

  const multi = isMultiLayout(packs);
  const sections = multi
    ? [
        ...preamble,
        buildRouterSection(targetDir, packs),
        buildSlimLawTable(targetDir, laws, packs),
        VERIFY_FOOTER,
      ]
    : [
        ...preamble,
        ...packNames.map((name) => readStackBody(targetDir, name)),
        buildLawTable(laws),
        VERIFY_FOOTER,
      ];

  const componentDirs = multi
    ? packs.flatMap((pack) => (pack.workdir === null ? [] : [pack.workdir]))
    : [];
  removeStaleComponentFiles(targetDir, new Set(componentDirs));

  writeRootSurfaces(targetDir, `${sections.join("\n\n")}\n`, selected);

  if (!multi) return;
  for (const pack of packs) {
    if (pack.workdir === null) continue;
    writeComponentPair(
      join(targetDir, pack.workdir),
      pack.workdir,
      buildComponentBody(pack.name, readStackBody(targetDir, pack.name)),
      selected,
    );
  }
}
