import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { VERSION } from "../version.js";

/**
 * The generated region inside a co owned agent instruction file.
 *
 * CLAUDE.md and AGENTS.md are not eep's files. A repository that already carries one carries it
 * because a team wrote it, and overwriting it (which every release through 0.2.2 did) destroyed the
 * only place that team had recorded how their own repository works. So the generated instructions
 * live inside a marked block, and everything outside the markers belongs to whoever put it there
 * and is never read, rewritten, or reordered by this program.
 *
 * The markers are HTML comments so they render as nothing in every markdown viewer, and the opening
 * one carries the version that wrote the block so a reader can tell a stale block from a current
 * one without diffing it.
 */
export const BLOCK_BEGIN_PREFIX = "<!-- eep:begin generated by eep ";
export const BLOCK_END = "<!-- eep:end -->";
export const BLOCK_BEGIN = `${BLOCK_BEGIN_PREFIX}${VERSION}; do not edit inside this block; regenerate with eep sync -->`;

/**
 * The first line inside every block.
 *
 * A brownfield CLAUDE.md often contradicts doctrine outright ("skip tests for prototypes"), and the
 * agent reading the file has two sets of instructions and no ordering between them. This states the
 * ordering once, at the top of the generated region, in the one document both instructions share.
 */
export const AUTHORITY_SENTENCE =
  "Where guidance in this repository conflicts with the laws below, the verify gate is the authority.";

/**
 * First line substrings that mark a file as one 0.1.x or 0.2.x generated whole.
 *
 * Those releases wrote the entire file, header and all, so there is no user content in it to
 * preserve and appending a block underneath would leave a second, stale copy of the instructions
 * above it. Both generated shapes are listed: the root document's header, and the per component
 * golden path header (see lib/generate.ts COMPONENT_HEADER_MARKER).
 */
const LEGACY_FIRST_LINE_MARKERS = [
  "# Agent instructions (generated by eep",
  "golden path (generated by eep ",
] as const;

/**
 * What writing the block into a given file will do, decided entirely by what is on disk now.
 *
 * `malformed` is the one state that writes nothing: a file carrying one marker, or an end before a
 * begin, has no region this program can identify, and guessing at one risks eating user content
 * between a stray marker and the real block.
 */
export type BlockState = "created" | "appended" | "refreshed" | "migrated" | "malformed";

export type BlockPlan = { state: BlockState; content: string | null };

function firstLine(text: string): string {
  return text.split("\n", 1)[0] ?? "";
}

function isLegacyGenerated(text: string): boolean {
  const first = firstLine(text);
  return LEGACY_FIRST_LINE_MARKERS.some((marker) => first.includes(marker));
}

type MarkerSpan = { begin: number; end: number } | null;

/**
 * Where the markers are, by line index, or null when there are none.
 *
 * Throws nothing: a malformed pairing is reported by returning the indices found so the caller can
 * tell "no block" from "half a block". The begin marker is matched on its version independent
 * prefix, because a block written by an older release must still be found and replaced by a newer
 * one.
 */
function findMarkers(lines: readonly string[]): { begin: number; end: number } {
  const begin = lines.findIndex((line) => line.startsWith(BLOCK_BEGIN_PREFIX));
  const end = lines.findIndex((line) => line.trim() === BLOCK_END);
  return { begin, end };
}

function markerSpan(lines: readonly string[]): MarkerSpan | "malformed" {
  const { begin, end } = findMarkers(lines);
  if (begin === -1 && end === -1) return null;
  if (begin === -1 || end === -1 || end < begin) return "malformed";
  return { begin, end };
}

// The block as text, without a trailing newline, so callers can splice it into a line array or
// terminate a whole file with it. The body arrives with the trailing newline generateAgentFiles
// puts there; it is stripped so the end marker always sits on the line after the last body line,
// whatever the body did at its end.
export function buildBlock(body: string): string {
  return [BLOCK_BEGIN, AUTHORITY_SENTENCE, "", body.replace(/\n+$/, ""), BLOCK_END].join("\n");
}

/**
 * The five write semantics, as one pure function over the file's current bytes.
 *
 * `existing` null means the file is absent. The returned `content` is the whole new file, or null
 * when nothing may be written (malformed only).
 *
 * Every branch is idempotent: running this twice over its own output returns the identical bytes,
 * because every branch except `malformed` produces a file carrying a well formed pair of markers,
 * which the next run resolves through the `refreshed` branch and nothing else.
 *
 * On `appended`, "preserve the existing content byte for byte" is honored over the content proper:
 * only the run of newlines at the very end of the file is normalized, to exactly one blank line of
 * separation. So a file that ended with a single newline (which is every well formed text file) is
 * a byte exact prefix of the result.
 */
export function planManagedBlock(existing: string | null, body: string): BlockPlan {
  const block = buildBlock(body);

  if (existing === null) return { state: "created", content: `${block}\n` };

  const lines = existing.split("\n");
  const span = markerSpan(lines);
  if (span === "malformed") return { state: "malformed", content: null };

  if (span !== null) {
    const above = lines.slice(0, span.begin);
    const below = lines.slice(span.end + 1);
    return { state: "refreshed", content: [...above, ...block.split("\n"), ...below].join("\n") };
  }

  if (isLegacyGenerated(existing)) return { state: "migrated", content: `${block}\n` };

  return { state: "appended", content: `${existing.replace(/\n+$/, "")}\n\n${block}\n` };
}

/**
 * The block removed and the file's own content kept, or null when the file was nothing but the
 * block.
 *
 * Used when a narrowing sync drops the pack whose component this file documents: the generated
 * region has to go, and a file that was entirely generated goes with it, but a directory where a
 * team wrote their own notes above our block keeps those notes.
 */
export function stripManagedBlock(existing: string): string | null {
  const lines = existing.split("\n");
  const span = markerSpan(lines);
  if (span === null || span === "malformed") return existing;
  const remainder = [...lines.slice(0, span.begin), ...lines.slice(span.end + 1)]
    .join("\n")
    .replace(/\n+$/, "");
  return remainder.trim() === "" ? null : `${remainder}\n`;
}

function readIfPresent(absPath: string): string | null {
  return existsSync(absPath) ? readFileSync(absPath, "utf8") : null;
}

/**
 * The state a write into this path would reach, without writing anything.
 *
 * The state depends only on what is on disk, never on the body about to be written, which is what
 * lets the plan a command prints before asking for consent be exact rather than indicative. See
 * planManagedBlock.
 */
export function managedBlockState(absPath: string): BlockState {
  return planManagedBlock(readIfPresent(absPath), "").state;
}

// Named for the reader who has to act on it: which file, what this program did instead, and the two
// repairs that make the next run succeed. Deliberately not fatal: one damaged file must not stop the
// other agent files, the vendored corpus, or the gate from being written.
function warnMalformed(relPath: string): void {
  console.warn(
    `eep: ${relPath} carries a malformed eep managed block and was left untouched; ` +
      `repair it by deleting the stray "${BLOCK_BEGIN_PREFIX}...-->" or "${BLOCK_END}" marker, ` +
      "or by deleting the whole block, then run the command again",
  );
}

/**
 * Writes `body` into `absPath` as a managed block, preserving everything the file already carried
 * outside the markers. `relPath` names the file in the malformed warning, so the reader sees the
 * path they typed rather than a temporary directory.
 *
 * Returns the state so a caller can report what it did. Creates the parent directory, because a
 * component instruction file can land in a directory a pack claims but nothing has created yet.
 */
export function writeManagedBlock(absPath: string, relPath: string, body: string): BlockState {
  const { state, content } = planManagedBlock(readIfPresent(absPath), body);
  if (content === null) {
    warnMalformed(relPath);
    return state;
  }
  mkdirSync(dirname(absPath), { recursive: true });
  writeFileSync(absPath, content);
  return state;
}
