import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { VERSION } from "../version.js";

/**
 * The generated region inside a co owned agent instruction file.
 *
 * CLAUDE.md and AGENTS.md are not eep's files. A repository that already carries one carries it
 * because a team wrote it, and overwriting it (which every release through 0.2.2 did) destroyed the
 * only place that team had recorded how their own repository works. So the generated instructions
 * live inside a marked block, and everything outside the markers belongs to whoever put it there
 * and is never read, rewritten, or reordered by this program.
 *
 * The markers are HTML comments so they render as nothing in every markdown viewer, and the opening
 * one carries the version that wrote the block so a reader can tell a stale block from a current
 * one without diffing it.
 */
export const BLOCK_BEGIN_PREFIX = "<!-- eep:begin generated by eep ";
export const BLOCK_END = "<!-- eep:end -->";
export const BLOCK_BEGIN = `${BLOCK_BEGIN_PREFIX}${VERSION}; do not edit inside this block; regenerate with eep sync -->`;

/**
 * The first line inside every block.
 *
 * A brownfield CLAUDE.md often contradicts doctrine outright ("skip tests for prototypes"), and the
 * agent reading the file has two sets of instructions and no ordering between them. This states the
 * ordering once, at the top of the generated region, in the one document both instructions share.
 */
export const AUTHORITY_SENTENCE =
  "Where guidance in this repository conflicts with the laws below, the verify gate is the authority.";

/**
 * The two shapes a file 0.1.x or 0.2.x generated whole opens with, anchored to the start of the
 * first line.
 *
 * Those releases wrote the entire file, header and all, so there is no user content in it to
 * preserve and appending a block underneath would leave a second, stale copy of the instructions
 * above it. Both generated shapes are covered: the root document's header, and the per component
 * golden path header (see lib/generate.ts COMPONENT_HEADER_MARKER).
 *
 * Anchored, not merely contained. A document whose opening line happens to mention the phrase, which
 * is exactly what a repository's own onboarding notes about eep would do, is user content, and
 * matching it mid line would replace that entire file with generated text.
 */
const LEGACY_ROOT_HEADER = "# Agent instructions (generated by eep";
const LEGACY_COMPONENT_HEADER = /^# \S.* golden path \(generated by eep /;

/**
 * What writing the block into a given file will do, decided entirely by what is on disk now.
 *
 * `malformed` is the one state that writes nothing: a file carrying one marker, or an end before a
 * begin, has no region this program can identify, and guessing at one risks eating user content
 * between a stray marker and the real block.
 */
export type BlockState = "created" | "appended" | "refreshed" | "migrated" | "malformed";

/**
 * `extraBlocks` reports a second well formed block below the one being refreshed. It is never acted
 * on, only reported: additional blocks are almost certainly the residue of a merge, and deleting a
 * region of somebody's file on a guess is the failure this whole module exists to prevent.
 */
export type BlockPlan = { state: BlockState; content: string | null; extraBlocks: boolean };

function firstLine(text: string): string {
  return text.split("\n", 1)[0] ?? "";
}

function isLegacyGenerated(text: string): boolean {
  const first = firstLine(text);
  return first.startsWith(LEGACY_ROOT_HEADER) || LEGACY_COMPONENT_HEADER.test(first);
}

// Fenced code block delimiters, matched exactly as lib/markdown.ts matches them, so a marker quoted
// inside a fence is recognized as prose about eep by both the style scanner and this one.
const FENCE_PATTERN = /^\s*(```|~~~)/;

type MarkerScan =
  | { kind: "none" }
  | { kind: "malformed" }
  | { kind: "found"; begin: number; end: number; extra: boolean };

function nextNonBlank(lines: readonly string[], from: number): string | null {
  for (let index = from; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (line.trim() !== "") return line;
  }
  return null;
}

/**
 * Every marker line this program wrote, and nothing that merely looks like one.
 *
 * Two guards, and both are load bearing, because a marker is a string a repository is entirely
 * likely to write about itself: a CLAUDE.md documenting how eep works will quote both markers, and
 * a document explaining the block will paste one into a fenced example.
 *
 * First, lines inside an open fence are skipped outright. A quoted example is prose, and treating it
 * as a marker would let this function pick a begin from inside a code sample and an end from the
 * real block below it, replacing everything between them.
 *
 * Second, a begin candidate counts only when the next non blank line is the authority sentence,
 * which is the one line this program always writes immediately under it. Without that, a user who
 * pastes the begin marker into their own prose and keeps writing has handed this function a region
 * that starts in their sentences and ends at the real block, and refreshing it would delete every
 * word in between. The cost of the guard is that a block whose authority sentence a human deleted
 * stops being recognized; that lands in `malformed`, which writes nothing and says so, rather than
 * anywhere that loses bytes.
 *
 * End candidates need no second guard: an end without a qualifying begin is `malformed` already, and
 * `malformed` never writes.
 */
function scanMarkers(lines: readonly string[]): MarkerScan {
  const begins: number[] = [];
  const ends: number[] = [];
  let inFence = false;

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (FENCE_PATTERN.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    if (line.startsWith(BLOCK_BEGIN_PREFIX)) {
      if (nextNonBlank(lines, index + 1)?.trim() === AUTHORITY_SENTENCE) begins.push(index);
      continue;
    }
    if (line.trim() === BLOCK_END) ends.push(index);
  }

  if (begins.length === 0 && ends.length === 0) return { kind: "none" };

  const begin = begins[0];
  const end = ends[0];
  if (begin === undefined || end === undefined || end < begin) return { kind: "malformed" };

  const nextBegin = begins.find((index) => index > end);
  const extra = nextBegin !== undefined && ends.some((index) => index > nextBegin);
  return { kind: "found", begin, end, extra };
}

// The block as text, without a trailing newline, so callers can splice it into a line array or
// terminate a whole file with it. The body arrives with the trailing newline generateAgentFiles
// puts there; it is stripped so the end marker always sits on the line after the last body line,
// whatever the body did at its end.
export function buildBlock(body: string): string {
  return [BLOCK_BEGIN, AUTHORITY_SENTENCE, "", body.replace(/\n+$/, ""), BLOCK_END].join("\n");
}

/**
 * The five write semantics, as one pure function over the file's current bytes.
 *
 * `existing` null means the file is absent. The returned `content` is the whole new file, or null
 * when nothing may be written (malformed only).
 *
 * Every branch is idempotent: running this twice over its own output returns the identical bytes,
 * because every branch except `malformed` produces a file carrying a well formed pair of markers,
 * which the next run resolves through the `refreshed` branch and nothing else.
 *
 * On `appended`, "preserve the existing content byte for byte" is honored over the content proper:
 * only the run of newlines at the very end of the file is normalized, to exactly one blank line of
 * separation. So a file that ended with a single newline (which is every well formed text file) is
 * a byte exact prefix of the result.
 */
export function planManagedBlock(existing: string | null, body: string): BlockPlan {
  const block = buildBlock(body);

  if (existing === null) {
    return { state: "created", content: `${block}\n`, extraBlocks: false };
  }

  const lines = existing.split("\n");
  const scan = scanMarkers(lines);
  if (scan.kind === "malformed") {
    return { state: "malformed", content: null, extraBlocks: false };
  }

  if (scan.kind === "found") {
    const above = lines.slice(0, scan.begin);
    const below = lines.slice(scan.end + 1);
    return {
      state: "refreshed",
      content: [...above, ...block.split("\n"), ...below].join("\n"),
      extraBlocks: scan.extra,
    };
  }

  if (isLegacyGenerated(existing)) {
    return { state: "migrated", content: `${block}\n`, extraBlocks: false };
  }

  return {
    state: "appended",
    content: `${existing.replace(/\n+$/, "")}\n\n${block}\n`,
    extraBlocks: false,
  };
}

/**
 * The block removed and the file's own content kept, or null when the file was nothing but the
 * block.
 *
 * Used when a narrowing sync drops the pack whose component this file documents: the generated
 * region has to go, and a file that was entirely generated goes with it, but a directory where a
 * team wrote their own notes above our block keeps those notes.
 */
export function stripManagedBlock(existing: string): string | null {
  const lines = existing.split("\n");
  const scan = scanMarkers(lines);
  if (scan.kind !== "found") return existing;
  const remainder = [...lines.slice(0, scan.begin), ...lines.slice(scan.end + 1)]
    .join("\n")
    .replace(/\n+$/, "");
  return remainder.trim() === "" ? null : `${remainder}\n`;
}

function readIfPresent(absPath: string): string | null {
  return existsSync(absPath) ? readFileSync(absPath, "utf8") : null;
}

/**
 * The state a write into this path would reach, without writing anything.
 *
 * The state depends only on what is on disk, never on the body about to be written, which is what
 * lets the plan a command prints before asking for consent be exact rather than indicative. See
 * planManagedBlock.
 */
export function managedBlockState(absPath: string): BlockState {
  return planManagedBlock(readIfPresent(absPath), "").state;
}

// Named for the reader who has to act on it: which file, what this program did instead, and the two
// repairs that make the next run succeed. Deliberately not fatal: one damaged file must not stop the
// other agent files, the vendored corpus, or the gate from being written.
function warnMalformed(relPath: string): void {
  console.warn(
    `eep: ${relPath} carries a malformed eep managed block and was left untouched; ` +
      `repair it by deleting the stray "${BLOCK_BEGIN_PREFIX}...-->" or "${BLOCK_END}" marker, ` +
      "or by deleting the whole block, then run the command again",
  );
}

// A second well formed block below the first is almost always merge residue, and it is stale the
// moment the first is refreshed. Reported rather than deleted: the region is somebody's file, and a
// program that silently removes a section of it on a guess is the failure this module exists to
// prevent. The first block is still refreshed, so the gate's instructions are current either way.
function warnExtraBlocks(relPath: string): void {
  console.warn(
    `eep: ${relPath} carries more than one eep managed block; the first was refreshed and the ` +
      "additional stale blocks below it were left in place; delete them by hand",
  );
}

/**
 * Writes `body` into `absPath` as a managed block, preserving everything the file already carried
 * outside the markers. `relPath` names the file in the malformed warning, so the reader sees the
 * path they typed rather than a temporary directory.
 *
 * Returns the state so a caller can report what it did. Creates the parent directory, because a
 * component instruction file can land in a directory a pack claims but nothing has created yet.
 */
export function writeManagedBlock(absPath: string, relPath: string, body: string): BlockState {
  const { state, content, extraBlocks } = planManagedBlock(readIfPresent(absPath), body);
  if (content === null) {
    warnMalformed(relPath);
    return state;
  }
  mkdirSync(dirname(absPath), { recursive: true });
  writeFileSync(absPath, content);
  if (extraBlocks) warnExtraBlocks(relPath);
  return state;
}
