import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { generateAgentFiles } from "../src/lib/generate.js";
import { repoRoot } from "../src/lib/schema.js";
import { vendorInto } from "../src/lib/vendor.js";

// Built from escapes, not literal glyphs, so this test file's own source never embeds a banned
// dash even though two assertions below check the generated output contains none.
const EM_DASH = "\u2014";
const EN_DASH = "\u2013";

function newVendoredTarget(): string {
  const dir = mkdtempSync(join(tmpdir(), "eep-generate-"));
  vendorInto(dir, repoRoot(), ["python-fastapi"], "greenfield");
  return dir;
}

describe("generateAgentFiles", () => {
  let tmp: string;

  beforeEach(() => {
    tmp = newVendoredTarget();
  });

  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it("writes AGENTS.md and CLAUDE.md as byte identical files", () => {
    generateAgentFiles(tmp);

    expect(existsSync(join(tmp, "AGENTS.md"))).toBe(true);
    expect(existsSync(join(tmp, "CLAUDE.md"))).toBe(true);
    const agents = readFileSync(join(tmp, "AGENTS.md"));
    const claude = readFileSync(join(tmp, "CLAUDE.md"));
    expect(agents.equals(claude)).toBe(true);
  });

  it("opens with the generated header line and the profile block", () => {
    generateAgentFiles(tmp);
    const content = readFileSync(join(tmp, "AGENTS.md"), "utf8");

    expect(content).toContain(
      "# Agent instructions (generated by eep 0.1.0; do not edit, regenerate with eep adopt)",
    );
    expect(content).toContain(
      "Profile: greenfield. Every law blocks. Scaffold with eep init output patterns; never hand roll what a template covers.",
    );
  });

  it("includes the constitution body and the pack's STACK.md golden path", () => {
    generateAgentFiles(tmp);
    const content = readFileSync(join(tmp, "AGENTS.md"), "utf8");

    expect(content).toContain("twelve tenets");
    expect(content).toContain("golden path");
  });

  it("includes a law table row for an implemented law and for a declined law", () => {
    generateAgentFiles(tmp);
    const content = readFileSync(join(tmp, "AGENTS.md"), "utf8");

    expect(content).toContain("## The laws in force");
    expect(content).toContain("| Law | Title | Severity | Check |");

    const implementedRow = content.split("\n").find((line) => line.includes("EEP-TEST-03"));
    expect(implementedRow).toBeDefined();
    expect(implementedRow).toContain("`");

    const declinedRow = content.split("\n").find((line) => line.includes("EEP-DOCS-03"));
    expect(declinedRow).toBeDefined();
    expect(declinedRow).toContain("declined");
  });

  it("ends with the verify footer and contains no dash characters or unstripped footers", () => {
    generateAgentFiles(tmp);
    const content = readFileSync(join(tmp, "AGENTS.md"), "utf8");

    expect(content).toContain(
      "Before declaring work done run `eep verify`. On failure run `eep explain <LAW-ID>`.",
    );
    expect(content.includes(EM_DASH)).toBe(false);
    expect(content.includes(EN_DASH)).toBe(false);

    const lines = content.split("\n");
    for (let i = 0; i < lines.length - 1; i++) {
      if ((lines[i] ?? "").trim() === "---") {
        expect((lines[i + 1] ?? "").startsWith("*Authored by")).toBe(false);
      }
    }
  });

  it("throws when .eep is missing", () => {
    const empty = mkdtempSync(join(tmpdir(), "eep-generate-empty-"));
    try {
      expect(() => generateAgentFiles(empty)).toThrow("run eep adopt first");
    } finally {
      rmSync(empty, { recursive: true, force: true });
    }
  });
});
